version: '3.8'

services:
  mysql:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
    ports:
      - 3306:3306
  
  task:
    image: node:18
    working_dir: /app
    volumes:
      - ./task:/app/task
    ports:
      - 5000:5000
    stdin_open: true